language: java 
jdk:  
  openjdk6 
script: 
  mvn install
notifications:
  email:
    recipients:
      - vignesh.murugan@one.verizon.com
      - vijay.raghunathkm@one.verizon.com
deploy:
  edge:true
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username:
    secure: "vignesh.murugan@one.verizon.com"
  password:
    secure: "vicky59"
  organization: VDSI-MyApp
  space: development
  on:
    repo: vignesh5989/MyApp
    branch: master
